## Introduction to Numpy

NumPy(Numerical Python) 是 Python 语言的一个扩展程序库，支持大量的维度数组与矩阵运算，此外也针对数组运算提供大量的数学函数库。

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


### 0.引入Numpy包

In [2]:
import numpy as np

### 1.NumPy Ndarray 对象

In [3]:
a = np.array([1,2,3])  
print (a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


### 2.创建Ndarray

1)强制类型转换

In [4]:
list = [1,2,3,4,5,6,7]
print(list)
print(type(list))

[1, 2, 3, 4, 5, 6, 7]
<class 'list'>


In [5]:
list = np.array(list)
print(list)
print(type(list))

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


2）直接创建

In [6]:
list = np.array([1,2,3,4,5,6,7])  
print(list)
print(type(list))

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


3）numpy.empty(shape, dtype = float, order = 'C')

In [7]:
list = np.empty([7], dtype = int) 
print(list)
print(type(list))

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


4)numpy.zeros(shape, dtype = float, order = 'C')

In [8]:
list = np.zeros(7) 
print(list)
print(type(list))

[0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


5)numpy.ones(shape, dtype = None, order = 'C')

In [9]:
list = np.ones(7) 
print(list)
print(type(list))

[1. 1. 1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


6)**One-hot Encoder**

In [10]:
def transform_one_hot(labels):
  n_labels = np.max(labels) + 1
  one_hot = np.eye(n_labels)[labels]
  return one_hot.reshape(len(one_hot),1,len(one_hot[0]))
list = np.array([1,2,3,4,5,6,7]) 
list = transform_one_hot(list)
print(list)
print(type(list))

[[[0. 1. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 1. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 1. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 1. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 1. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 1. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 1.]]]
<class 'numpy.ndarray'>


7)numpy.arange(start, stop, step, dtype)

In [11]:
list = np.arange(7)  
print(list)
print(type(list))

[0 1 2 3 4 5 6]
<class 'numpy.ndarray'>


8)numpy.linspace 函数用于创建一个一维数组，数组是一个等差数列构成的，格式如下：

np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

In [12]:
list = np.linspace(1,1,10)
print(list)
print(type(list))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


9)np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)

In [14]:
list = np.logspace(0,9,10,base=2)
print(list)
print(type(list))

[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]
<class 'numpy.ndarray'>


### 3.ndarray属性

ndarray.ndim

In [27]:
list = np.array([1,2,3,4,5,6,7]) 
print(list.ndim)

1


In [30]:
list = np.array([[1,2],[3,4],[5,6]])
print(list.ndim)

2


In [29]:
list = np.array([[1,2,3,4,5,6,7]])
print(list.ndim)

2


ndarray.shape

In [31]:
list = np.array([[1,2],[3,4],[5,6]])
print(list.shape)

(3, 2)


### 4.切片与索引 

切片

In [18]:
a = np.arange(10)
s = slice(2,7,2)   # 从索引 2 开始到索引 7 停止，间隔为2
print(type(s))
print(s)
print(type(a[s]))
print (a[s])

<class 'slice'>
slice(2, 7, 2)
<class 'numpy.ndarray'>
[2 4 6]


通过冒号分隔切片参数 start:stop:step 来进行切片操作：

In [19]:
a = np.arange(10)  
b = a[2:7:2]   # 从索引 2 开始到索引 7 停止，间隔为 2
print(b)

[2 4 6]


冒号 : 的解释：如果只放置一个参数，如 [2]，将返回与该索引相对应的单个元素。如果为 [2:]，表示从该索引开始以后的所有项都将被提取。如果使用了两个参数，如 [2:7]，那么则提取两个索引(不包括停止索引)之间的项。

In [24]:
a = np.arange(10)  # [0 1 2 3 4 5 6 7 8 9]
b = a[2] 
print(b)

2


In [25]:
print(a[2:])

[2 3 4 5 6 7 8 9]


In [26]:
print(a[2:5])

[2 3 4]


高维数组

In [33]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)
print(a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
[[3 4 5]
 [4 5 6]]


切片还可以包括省略号 …，来使选择元组的长度与数组的维度相同。 如果在行位置使用省略号，它将返回包含行中元素的 ndarray。

In [34]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])  
print (a[...,1])   # 第2列元素
print (a[1,...])   # 第2行元素
print (a[...,1:])  # 第2列及剩下的所有元素

[2 4 5]
[3 4 5]
[[2 3]
 [4 5]
 [5 6]]


### 5.广播 

广播(Broadcast)是 numpy 对不同形状(shape)的数组进行数值计算的方式

如果两个数组 a 和 b 形状相同，即满足 a.shape == b.shape，那么 a*b 的结果就是 a 与 b 数组对应位相乘。

In [35]:
a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
print (c)

[ 10  40  90 160]


当运算中的 2 个数组的形状不同时，numpy 将自动触发广播机制。

In [36]:
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([1,2,3])
print(a + b)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


### 6.迭代数组 

In [38]:
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
print ('原始数组是：')
print (a)
print ('\n')
print ('迭代输出元素：')
for x in np.nditer(a):
    print (x, end=", " )
print ('\n')

原始数组是：
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


迭代输出元素：
0, 0, 0, 10, 10, 10, 20, 20, 20, 30, 30, 30, 



### 7.数组操作 

1)**修改数组形状**

In [40]:
a = np.arange(8)
print(a)
print(a.shape)
print(type(a.shape))

[0 1 2 3 4 5 6 7]
(8,)
<class 'tuple'>


In [41]:
a = a.reshape(2,4)
print(a)
print(a.shape)

[[0 1 2 3]
 [4 5 6 7]]
(2, 4)


In [42]:
a = a.reshape(2,1,4)
print(a)
print(a.shape)

[[[0 1 2 3]]

 [[4 5 6 7]]]
(2, 1, 4)


2)翻转数组(转置)

In [53]:
a = a.reshape(2,4)

In [54]:
print(a)
print(a.shape)

[[0 1 2 3]
 [4 5 6 7]]
(2, 4)


In [55]:
print(a.T)
print(a.shape)

[[0 4]
 [1 5]
 [2 6]
 [3 7]]
(2, 4)


In [56]:
a = a.reshape(2,1,4)
print(a)
print(a.shape)

[[[0 1 2 3]]

 [[4 5 6 7]]]
(2, 1, 4)


In [57]:
print(a.T)
print(a.T.shape)

[[[0 4]]

 [[1 5]]

 [[2 6]]

 [[3 7]]]
(4, 1, 2)


3)**连接数组**

numpy.concatenate 函数用于沿指定轴连接相同形状的两个或多个数组，格式如下：

numpy.concatenate((a1, a2, ...), axis)

a1, a2, ...：相同类型的数组

axis：沿着它连接数组的轴，默认为 0

In [58]:
a = np.array([[1,2],[3,4]])
 
print ('第一个数组：')
print (a)
print ('\n')
b = np.array([[5,6],[7,8]])
 
print ('第二个数组：')
print (b)
print ('\n')
# 两个数组的维度相同
 
print ('沿轴 0 连接两个数组：')
print (np.concatenate((a,b)))
print ('\n')
 
print ('沿轴 1 连接两个数组：')
print (np.concatenate((a,b),axis = 1))

第一个数组：
[[1 2]
 [3 4]]


第二个数组：
[[5 6]
 [7 8]]


沿轴 0 连接两个数组：
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


沿轴 1 连接两个数组：
[[1 2 5 6]
 [3 4 7 8]]


4）分割数组

In [59]:
a = np.arange(9)
 
print ('第一个数组：')
print (a)
print ('\n')
 
print ('将数组分为三个大小相等的子数组：')
b = np.split(a,3)
print (b)
print ('\n')
 
print ('将数组在一维数组中表明的位置分割：')
b = np.split(a,[4,7])
print (b)

第一个数组：
[0 1 2 3 4 5 6 7 8]


将数组分为三个大小相等的子数组：
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


将数组在一维数组中表明的位置分割：
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]


5）numpy.resize

In [60]:
a = np.array([[1,2,3],[4,5,6]])
 
print ('第一个数组：')
print (a)
print ('\n')
 
print ('第一个数组的形状：')
print (a.shape)
print ('\n')
b = np.resize(a, (3,2))
 
print ('第二个数组：')
print (b)
print ('\n')
 
print ('第二个数组的形状：')
print (b.shape)
print ('\n')
# 要注意 a 的第一行在 b 中重复出现，因为尺寸变大了
 
print ('修改第二个数组的大小：')
b = np.resize(a,(3,3))
print (b)

第一个数组：
[[1 2 3]
 [4 5 6]]


第一个数组的形状：
(2, 3)


第二个数组：
[[1 2]
 [3 4]
 [5 6]]


第二个数组的形状：
(3, 2)


修改第二个数组的大小：
[[1 2 3]
 [4 5 6]
 [1 2 3]]


6）numpy.unique

In [61]:
a = np.array([5,2,6,2,7,5,6,8,2,9])
 
print ('第一个数组：')
print (a)
print ('\n')
 
print ('第一个数组的去重值：')
u = np.unique(a)
print (u)
print ('\n')

第一个数组：
[5 2 6 2 7 5 6 8 2 9]


第一个数组的去重值：
[2 5 6 7 8 9]




### 8.算数函数 

In [62]:
a = np.arange(9, dtype = np.float_).reshape(3,3)  
print ('第一个数组：')
print (a)
print ('\n')
print ('第二个数组：')
b = np.array([10,10,10])  
print (b)
print ('\n')
print ('两个数组相加：')
print (np.add(a,b))
print ('\n')
print ('两个数组相减：')
print (np.subtract(a,b))
print ('\n')
print ('两个数组相乘：')
print (np.multiply(a,b))
print ('\n')
print ('两个数组相除：')
print (np.divide(a,b))

第一个数组：
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


第二个数组：
[10 10 10]


两个数组相加：
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]


两个数组相减：
[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]


两个数组相乘：
[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]


两个数组相除：
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


### 9.统计函数 

1）最大、最小值

In [64]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]])  
print ('我们的数组是：')
print (a)
print ('\n')
print ('调用 amin() 函数：')
print (np.amin(a,1))
print ('\n')
print ('再次调用 amin() 函数：')
print (np.amin(a,0))
print ('\n')
print ('调用 amax() 函数：')
print (np.amax(a))
print ('\n')
print ('再次调用 amax() 函数：')
print (np.amax(a, axis =  0))

我们的数组是：
[[3 7 5]
 [8 4 3]
 [2 4 9]]


调用 amin() 函数：
[3 3 2]


再次调用 amin() 函数：
[2 4 3]


调用 amax() 函数：
9


再次调用 amax() 函数：
[8 7 9]


2）百分位数

第 p 个百分位数是这样一个值，它使得至少有 p% 的数据项小于或等于这个值，且至少有 (100-p)% 的数据项大于或等于这个值。

In [69]:
a = np.array([[10, 7, 4], [3, 2, 1]])
print (a)
print ('50% 的分位数:{}'.format(np.percentile(a, 50))) 

[[10  7  4]
 [ 3  2  1]]
50% 的分位数:3.5


3)中位数

In [71]:
a = np.array([[30,65,70],[80,95,10],[50,90,60]])  
print (a)
print ('\n')
print ('中位数：')
print (np.median(a))

[[30 65 70]
 [80 95 10]
 [50 90 60]]


中位数：
65.0


4）平均数

In [72]:
print ('平均数：')
print(np.mean(a))

平均数：
61.111111111111114


In [73]:
a = np.array([1,2,4,5,6,7])

5)标准差

In [74]:
print(np.std(a))

2.1147629234082532


6)方差

In [75]:
print(np.var(a))

4.472222222222222


### 10.排序 

In [77]:
a = np.array([7,3,4,8,10,19,77,16,25])
print(a)
print(np.sort(a))

[ 7  3  4  8 10 19 77 16 25]
[ 3  4  7  8 10 16 19 25 77]


### 11. 矩阵库

1)转置矩阵

In [78]:
a = np.arange(12).reshape(3,4)
 
print ('原矩阵：')
print (a)
print ('\n')
 
print ('转置矩阵：')
print (a.T)

原矩阵：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


转置矩阵：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


2）matlib.empty()

In [82]:
import numpy.matlib 

In [85]:
print (np.matlib.empty((2,2)))
print (type(np.matlib.empty((2,2))))

[[0.0e+000 1.5e-323]
 [3.0e-323 4.4e-323]]
<class 'numpy.matrix'>


3)numpy.matlib.zeros()

In [86]:
print (np.matlib.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


4)numpy.matlib.ones()

In [87]:
print (np.matlib.ones((2,2)))

[[1. 1.]
 [1. 1.]]


5)numpy.matlib.eye()

numpy.matlib.eye(n, M,k, dtype)

n: 返回矩阵的行数

M: 返回矩阵的列数，默认为 n

k: 对角线的索引

dtype: 数据类型

In [89]:
print (np.matlib.eye(n =  3, M =  4, k =  0, dtype =  float))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


6)numpy.matlib.identity()

numpy.matlib.identity() 函数返回给定大小的单位矩阵。

In [90]:
print (np.matlib.identity(5, dtype =  float))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


**矩阵总是二维的，而 ndarray 是一个 n 维数组。**

### 12.线性代数 

1）内积

In [91]:
a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])
print(np.dot(a,b))

[[37 40]
 [85 92]]


2）点积

In [92]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
print (np.vdot(a,b))

130


3）行列式

In [94]:
a = np.array([[1,2], [3,4]]) 
 
print (np.linalg.det(a))

-2.0000000000000004


4）求逆

In [95]:
x = np.array([[1,2],[3,4]]) 
y = np.linalg.inv(x) 
print (x)
print (y)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


5）求解线性矩阵方程

In [97]:
import numpy as np 
 
a = np.array([[1,1,1],[0,2,5],[2,5,-1]]) 
 
print ('数组 a：')
print (a)
ainv = np.linalg.inv(a) 
 
print ('a 的逆：')
print (ainv)
 
print ('矩阵 b：')
b = np.array([[6],[-4],[27]]) 
print (b)
 
print ('计算：A^(-1)B：')
print(np.dot(ainv,b))

print ('使用函数solve求解')
x = np.linalg.solve(a,b) 
print (x)
# 这就是线性方向 x = 5, y = 3, z = -2 的解

数组 a：
[[ 1  1  1]
 [ 0  2  5]
 [ 2  5 -1]]
a 的逆：
[[ 1.28571429 -0.28571429 -0.14285714]
 [-0.47619048  0.14285714  0.23809524]
 [ 0.19047619  0.14285714 -0.0952381 ]]
矩阵 b：
[[ 6]
 [-4]
 [27]]
计算：A^(-1)B：
[[ 5.]
 [ 3.]
 [-2.]]
使用函数solve求解
[[ 5.]
 [ 3.]
 [-2.]]
